# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 走路赚

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  watch:
    types: started
  repository_dispatch:
    types: zouluzhuan
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        TZ: Asia/shanghai
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: |
          npm install
      - name: '运行 【走路赚】'
        run: |
          node Scripts/zouluzhuan.js
        env:
          XIAOMUYUHEADER: ${{ secrets. XIAOMUYUHEADER }}
          IBOXPAYBODY: ${{ secrets. IBOXPAYBODY }}
          TURNTABLRURL: ${{ secrets. TURNTABLRURL }}
          TURNTABLRHEADER: ${{ secrets. TURNTABLRHEADER }}
          DOUBLEHEADER: ${{ secrets. DOUBLEHEADER }}
          CARDBODY: ${{ secrets. CARDBODY }}
          MEMBERBODY: ${{ secrets. MEMBERBODY }}
          DRINKBODY: ${{ secrets. DRINKBODY }}

          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
          IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY }}
